[package]
name = "lvp"
version = "0.2.0"
edition = "2024"

[dependencies]
aws-config = { version = "1.8.13", features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.120.0", features = ["behavior-version-latest"] }
clap = { version = "4.5.58", features = ["derive", "env"] }
fastrand = "2.3.0"
futures = "0.3.31"
ndarray = "0.17.2"
snafu = "0.8.9"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
url = "2.5.8"
video-rs = { version = "0.10.5", features = ["ndarray"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
missing_docs_in_private_items = "warn"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
